services:
  postgres:
    image: postgres:18-alpine
    restart: on-failure
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${SPRING_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATABASE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATABASE_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SPRING_DATABASE_USERNAME} -d ${SPRING_DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.6.1-alpine
    restart: on-failure
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: khatkevichmatsvei/authservice
    restart: on-failure
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: